{
 "title": "Network",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "LISTA DISPOSITIVOS",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    ip_address, \n    mac_address, \n    MAX(scan_date) AS latest_scan_date\nFROM \n    network_devices\nGROUP BY \n    ip_address, \n    mac_address\nORDER BY \n    latest_scan_date DESC;\n"
    }
   ]
  },
  {
   "title": "ACTIVOS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    COUNT(DISTINCT ip_address) AS unique_ip_count\nFROM \n    network_devices\nWHERE \n    scan_date >= (SELECT MAX(scan_date) FROM network_devices) - INTERVAL '1 minute';\n"
    }
   ]
  },
  {
   "title": "ARP PACKETs SEND",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(ip_address) FROM network_devices LIMIT 50 "
    }
   ]
  },
  {
   "title": "TIME LINE",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('minute', scan_date) AS time_interval,\n    COUNT(DISTINCT ip_address) AS unique_ip_count\nFROM \n    network_devices\nGROUP BY \n    DATE_TRUNC('minute', scan_date)\nORDER BY \n    time_interval DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "LAST RECORD",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT MAX(scan_date) FROM network_devices LIMIT 50 "
    }
   ]
  }
 ]
}